# Generated by Django 5.2.4 on 2025-07-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('content', models.TextField()),
                ('reply_to', models.CharField(blank=True, null=True)),
                ('published_date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(choices=[('pending', '대기'), ('in_progress', '처리중'), ('resolved', '완료')], default='pending', max_length=20)),
                ('ip', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, max_length=256)),
            ],
        ),
    ]
